FROM ubuntu:14.04
MAINTAINER Ray Wang <raywang945@gmail.com>
RUN apt-get update && apt-get install -y \
    gcc \
    make \
    gdb \
    valgrind \
    libpolarssl5 \
    libpolarssl-dev \
    iperf \
    tcpdump \
    wget \
    openssl \
    firefox \
    tmux \
    vim \
    python \
    iptables
WORKDIR /workspace/
