EXTRA_CFLAGS +=
APP_EXTRA_FLAGS:= -O2 -ansi -pedantic
KERNEL_SRC:= /lib/modules/$(shell uname -r)/build
SUBDIR= $(PWD)
GCC:=gcc
RM:=rm

.PHONY : clean

all: clean modules app

obj-m:= mp2.o

modules:
	$(MAKE) -C $(KERNEL_SRC) M=$(SUBDIR) modules

app: userapp.c userapp.h
	$(GCC) -o userapp userapp.c

mapping: calculate_mapping.c userapp.h
	$(GCC) -o calculate_mapping calculate_mapping.c

clean:
	$(RM) -rf userapp calculate_mapping .*.cmd .tmp_versions *~ *.ko *.o *.mod.c Module.symvers modules.order
